### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by gj52** [Lamarqe/fritzmesh#9]
Hi,

I have a fritzbox 6591 with OS 7.90-115370 BETA.
Nothing is in the panel.  No errors in the protocolls (HA and FB).

My second FB is a 7490 with OS 7.57.
I can see the mesh connection, but no devices.

Can I help to fix this?  More about me on https://github.com/gj52/gj52
Send me a PM ... can be in German or English ;-)

Thanks for your work.

**Comment by Lamarqe** [comment]
Regarding 6591, using 7.90:
I assume that AVM restructured their UI. The add-on makes assumptions to the structure of it.
In case update 7.90 gets also released to my FB7530, I will adopt the add-on to it.

Regarding 7490, using 7.57:
I can only guess that there is really no device connected directly to this FB.

**Comment by Lamarqe** [comment]
I started looking into FritzOS 8 tonight. I got the basics working but am stuck in some layouting aspects. 
Not sure when and if I will ever get this to work. AVM introduced obfuscation to their javascript. So they are intentionally trying to prevent things like I am doing. 

I might simply stop this addon, as I am really not willing to make their product more useful, but having to fight against their actions in order to do so.
